### ISSUE TITLE
Codinasion website

### ISSUE THREAD

**Issue by 0ME9A** [codinasion-archive/codinasion#11]
### What would you like to share?

Hey, @harshraj8843 the Codinasion website design is almost done.

Check out [`Figma`](https://www.figma.com/file/g8Ip1kmM3Zq0Hv0Tv43F4S/Codinasion?node-id=0%3A1&t=E1WGZHb9BcHzz3Kk-1)

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Access please !!!

**Comment by 0ME9A** [comment]
Approved

**Comment by harshraj8843** [comment]
Some issue from my side, i will let you know soon ⏳
