### ISSUE TITLE
Add some animations to the main page to improve UX

### ISSUE THREAD

**Issue by Petrosdevri** [codinasion-archive/codinasion#12]
### Description

I would like to implement some animations on the website (mainly the titles of the Contributors and Projects files) in order to improve user experience. I would like to ask whether you use Tailwind for styling, as this is what I saw after cloning the repo and due to Tailwind being kinda restrictive in terms of animations (of course I noticed there can be custom animations too). My proposal is to include fade in animations because they are quite frequent, time-efficient and require minimal code.

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Hey @Petrosdevri 

Thank you so much for taking the time to provide your valuable feedback. We greatly appreciate it. 

Our team is currently working on a new website design, led by @0ME9A. We would be delighted to have your contributions when it becomes available 🤗

**Comment by 0ME9A** [comment]
Hey guys our codinasion's website will be live for everyone very soon🤩
